"""empty message

Revision ID: 2dd8b0b6ee3d
Revises: None
Create Date: 2015-06-10 21:55:53.016986

"""

# revision identifiers, used by Alembic.
revision = '2dd8b0b6ee3d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('steam_id', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'steam_id')
    ### end Alembic commands ###
