"""empty message

Revision ID: 361c912a5b85
Revises: None
Create Date: 2014-07-28 21:23:31.961071

"""

# revision identifiers, used by Alembic.
revision = '361c912a5b85'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('cvp_uuid', sa.String(), nullable=True))
    op.create_index(u'ix_server_cvp_uuid', 'server', ['cvp_uuid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_server_cvp_uuid', table_name='server')
    op.drop_column('server', 'cvp_uuid')
    ### end Alembic commands ###
