"""empty message

Revision ID: 367b66df3c59
Revises: 62d3662ee0
Create Date: 2014-10-06 19:56:10.258578

"""

# revision identifiers, used by Alembic.
revision = '367b66df3c59'
down_revision = '62d3662ee0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('extensions', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'extensions')
    ### end Alembic commands ###
