"""empty message

Revision ID: 62d3662ee0
Revises: 361c912a5b85
Create Date: 2014-10-01 21:07:47.431795

"""

# revision identifiers, used by Alembic.
revision = '62d3662ee0'
down_revision = '361c912a5b85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('ip', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'ip')
    ### end Alembic commands ###
